# Generated by Django 4.0.3 on 2022-03-31 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_category_newproduct_category_productdesktop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newProduct', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=200)),
                ('stock', models.BooleanField(blank=True, default=True)),
                ('feature1', models.CharField(max_length=255)),
                ('feature2', models.CharField(max_length=255)),
                ('inTheBox1', models.CharField(max_length=50)),
                ('inTheBox2', models.CharField(max_length=50)),
                ('inTheBox3', models.CharField(max_length=50)),
                ('inTheBox4', models.CharField(max_length=50)),
                ('productImageMobile', models.ImageField(upload_to='images/')),
                ('productImageTablet', models.ImageField(upload_to='images/')),
                ('productImageDesktop', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
        ),
    ]
