# Generated by Django 4.0.3 on 2022-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_productgridimage1_product_productgridimage2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productGridImage1',
            new_name='productGridImage1Desktop',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productGridImage2',
            new_name='productGridImage1Mob',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productGridImage3',
            new_name='productGridImage1Tab',
        ),
        migrations.AddField(
            model_name='product',
            name='productGridImage2Desktop',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='productGridImage2Mob',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='productGridImage2Tab',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='productGridImage3Desktop',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='productGridImage3Mob',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='productGridImage3Tab',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
