# Generated by Django 4.0.3 on 2022-03-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_productgridimage1_product_productgridimage1desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nameProduct',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
