# Generated by Django 4.0.3 on 2022-03-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='newProduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='productDesktop',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='productMobile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='productTablet',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
