# Generated by Django 4.0.3 on 2022-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('newProduct', models.BooleanField(default=False)),
                ('productMobile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productTablet', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productDesktop', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
